### PR TITLE
Switch from avatar url to last activity url

### PR DESCRIPTION
**Pull request by nhorvath**
Sometime in October avatar url which was being used for the camera image stopped working. The current next best option is to switch to using the last activity's media url.
Hopefully, I will get a response about Skybell Connect and we can do a real implementation.

### CODE REVIEW

**Comment by nhorvath** [comment]
fixes https://github.com/home-assistant/home-assistant/issues/17617 and related issue https://github.com/MisterWil/skybellpy/issues/6

**Comment by MisterWil** [comment]
Thanks! Pushed this PR into a 0.2.0 release, however I noticed you released your own version. :-)

**Comment by nhorvath** [comment]
Yeah, but custom_compenents seems to not be picking it up in hassio for
some reason. Trying to figure that out now so I can test.

**Comment by MisterWil** [comment]
Custom components are hard to work with when overriding existing components. You have to change all of the imports in all of the files. I found it easier to just fork home-assistant, update the version, and then work with it that way.

**Comment by nhorvath** [comment]
Yeah, I've done that for other components I worked on but that was a new
one. I'm running with hassos so not really able to switch to a fork except
for testing on my laptop.

**Comment by MisterWil** [comment]
Yep, I also run HASSOS in a VM, so when I've developed/updated components in the past I also just run a second instance of HASS in a Linux VM with only that component set up.

**Comment by nhorvath** [comment]
ok, ill just do that and submit a pr with your new version.

**Pull request merged**
